Update dotnet-format.yml

diff --git a/.github/workflows/dotnet-format.yml b/.github/workflows/dotnet-format.yml
--- a/.github/workflows/dotnet-format.yml
+++ b/.github/workflows/dotnet-format.yml
@@ -3,6 +3,9 @@
 
 name: .NET format
 
+permissions:
+  contents: read
+
 on:
   push:
     branches: [ "main" ]
@@ -23,4 +26,10 @@ jobs:
     - name: Restore dependencies
       run: dotnet restore
     - name: Format
-      run: dotnet format --verify-no-changes --verbosity diagnostic
+      run: |
+        SLN_FILE=$(find . -name '*.sln' -print -quit)
+        if [ -z "$SLN_FILE" ]; then
+          echo "Solution file not found"
+          exit 1
+        fi
+        dotnet format "$SLN_FILE" --verify-no-changes --verbosity diagnostic
